
//Post Actions
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_LOADING = "GET_LIST_POST_LOADING";
export const GET_LIST_POST_ERROR = "GET_LIST_POST_ERROR";
export const REFRESH_LIST_POST = "REFRESH_LIST_POST";

export const LOADING_ADD_NEW_POST = "LOADING_ADD_NEW_POST";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const ADD_NEW_POST_ERROR = "ADD_NEW_POST_ERROR";

export const LIKE_POST = "LIKE_POST";
export const DISLIKE_POST = "DISLIKE_POST";

export const GET_SPECIFIC_POST_SUCCESS = "GET_SPECIFIC_POST_SUCCESS";
export const GET_SPECIFIC_POST_LOADING = "GET_SPECIFIC_POST_LOADING";
export const GET_SPECIFIC_POST_ERROR = "GET_SPECIFIC_POST_ERROR";

export const SUBMIT_COMMENT_LOADING = "SUBMIT_COMMENT_LOADING";
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS";
export const SUBMIT_COMMENT_ERROR = "SUBMIT_COMMENT_ERROR";


//ListChoice Actions
export const GET_LIST_PROVINCE_SUCCESS = "GET_LIST_PROVINCE_SUCCESS";
export const GET_LIST_PROVINCE_LOADING = "GET_LIST_PROVINCE_LOADING";
export const GET_LIST_PROVINCE_ERROR = "GET_LIST_PROVINCE_ERROR";
export const SELECT_PROVINCE = "SELECT_PROVINCE";
export const GET_LIST_CITY_SUCCESS = "GET_LIST_CITY_SUCCESS";
export const GET_LIST_CITY_LOADING = "GET_LIST_CITY_LOADING";
export const GET_LIST_CITY_ERROR = "GET_LIST_CITY_ERROR";
export const SELECT_CITY = "SELECT_CITY";

//List Skill Actions
export const ADD_SKILL_LOADING = "ADD_SKILL_LOADING";
export const ADD_SKILL_SUCCESS = "ADD_SKILL_SUCCESS";
export const ADD_SKILL_ERROR = "ADD_SKILL_ERROR";
export const UPDATE_SKILL_LOADING = "UPDATE_SKILL_LOADING";
export const UPDATE_SKILL_SUCCESS = "UPDATE_SKILL_SUCCESS";
export const UPDATE_SKILL_ERROR = "UPDATE_SKILL_ERROR";
export const DELETE_SKILL_LOADING = "DELETE_SKILL_LOADING";
export const DELETE_SKILL_SUCCESS = "DELETE_SKILL_SUCCESS";
export const DELETE_SKILL_ERROR = "DELETE_SKILL_ERROR";
export const UPDATE_IMPORTANT_SKILL = "UPDATE_IMPORTANT_SKILL";
export const SORT_DEFAULT_SKILL = "SORT_DEFAULT_SKILL";
export const SET_DEFAULT_SKILL = "SET_DEFAULT_SKILL";
export const ADD_DEFAULT_SKILL = "ADD_DEFAULT_SKILL";
export const ADD_REQUIRE_SKILL = "ADD_REQUIRE_SKILL";

//List University Actions
export const GET_LIST_UNI = "SET_LIST_UNI";
export const SELECT_UNI = "SELECT_UNI";
export const SEARCH_UNI = "SEARCH_UNI";

//List Matched Job Actions
export const GET_LIST_COMPANY_FILTER = "GET_LIST_COMPANY_FILTER";
export const SEARCH_COMPANY_FILTER = "SEARCH_COMPANY_FILTER";

//Login Actions
export const SAVE_ACCOUNT = "SAVE_ACCOUNT";

//Global User Actions
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const GET_USER_AND_SET_TO_GLOBAL = "GET_USER_AND_SET_TO_GLOBAL";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const ADD_EXPERIENCE_LOADING = "ADD_EXPERIENCE_LOADING";
export const ADD_EXPERIENCE_ERROR = "ADD_EXPERIENCE_ERROR";
export const UPDATE_EXPERIENCE_LOADING = "UPDATE_EXPERIENCE_LOADING";
export const UPDATE_EXPERIENCE_ERROR = "UPDATE_EXPERIENCE_ERROR";
export const DELETE_EXPERIENCE_LOADING = "DELETE_EXPERIENCE_LOADING";
export const DELETE_EXPERIENCE_ERROR = "DELETE_EXPERIENCE_ERROR";
export const ADD_EDUCATION_LOADING = "ADD_EDUCATION_LOADING";
export const ADD_EDUCATION_ERROR = "ADD_EDUCATION_ERROR";
export const UPDATE_EDUCATION_LOADING = "UPDATE_EDUCATION_LOADING";
export const UPDATE_EDUCATION_ERROR = "UPDATE_EDUCATION_ERROR";
export const DELETE_EDUCATION_LOADING = "DELETE_EDUCATION_LOADING";
export const DELETE_EDUCATION_ERROR = "DELETE_EDUCATION_ERROR";

// List Company Actions
export const GET_LIST_COMPANY = "GET_LIST_COMPANY";
export const GET_LIST_COMPANY_ERROR = "GET_LIST_COMPANY_ERROR";
export const SEARCH_COMPANY = "SEARCH_COMPANY";


//General User Actions
export const GET_INFO_GENERAL_USER = "GET_INFO_GENERAL_USER";

//Request Actions
export const SEND_REQUEST_LOADING = "SEND_REQUEST_LOADING";
export const SEND_REQUEST_SUCCESS = "SEND_REQUEST_SUCCESS";
export const SEND_REQUEST_ERROR = "SEND_REQUEST_ERROR";
export const NOT_RELATION = "NOT_RELATION";
export const YET_RELATION = "YET_RELATION";
export const WAITING_RELATION = "WAITING_RELATION";
export const DELETE_REQUEST_LOADING = "DELETE_REQUEST_LOADING";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_ERROR = "DELETE_REQUEST_ERROR";
export const GET_LIST_FRIEND_LOADING = "GET_LIST_FRIEND_LOADING";
export const GET_LIST_FRIEND_SUCCESS = "GET_LIST_FRIEND_SUCCESS";
export const GET_LIST_FRIEND_ERROR = "GET_LIST_FRIEND_ERROR";
export const DISCONNECT_LOADING = "DISCONNECT_LOADING";
export const DISCONNECT_SUCCESS = "DISCONNECT_SUCCESS";
export const DISCONNECT_ERROR = "DISCONNECT_ERROR";

//Requirement Actions
export const SUBMIT_REQUIREMENT_LOADING = "SUBMIT_REQUIREMENT_LOADING";
export const SUBMIT_REQUIREMENT_SUCCESS = "SUBMIT_REQUIREMENT_SUCCESS";
export const SUBMIT_REQUIREMENT_ERROR = "SUBMIT_REQUIREMENT_ERROR";

