
//Post Actions
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";
export const GET_LIST_POST_LOADING = "GET_LIST_POST_LOADING";
export const GET_LIST_POST_ERROR = "GET_LIST_POST_ERROR";
export const REFRESH_LIST_POST = "REFRESH_LIST_POST";

export const LOADING_ADD_NEW_POST = "LOADING_ADD_NEW_POST";
export const ADD_NEW_POST_SUCCESS = "ADD_NEW_POST_SUCCESS";
export const ADD_NEW_POST_ERROR = "ADD_NEW_POST_ERROR";

//ListChoice Actions
export const GET_LIST_PROVINCE_SUCCESS = "GET_LIST_PROVINCE_SUCCESS";
export const GET_LIST_PROVINCE_LOADING = "GET_LIST_PROVINCE_LOADING";
export const GET_LIST_PROVINCE_ERROR = "GET_LIST_PROVINCE_ERROR";
export const SELECT_PROVINCE = "SELECT_PROVINCE";
export const GET_LIST_CITY_SUCCESS = "GET_LIST_CITY_SUCCESS";
export const GET_LIST_CITY_LOADING = "GET_LIST_CITY_LOADING";
export const GET_LIST_CITY_ERROR = "GET_LIST_CITY_ERROR";
export const SELECT_CITY = "SELECT_CITY";

//List Skill Actions
export const ADD_SKILL = "ADD_SKILL";
export const DELETE_SKILL = "DELETE_SKILL";
export const UPDATE_IMPORTANT_SKILL = "UPDATE_IMPORTANT_SKILL";
export const SORT_DEFAULT_SKILL = "SORT_DEFAULT_SKILL";
export const SET_DEFAULT_SKILL = "SET_DEFAULT_SKILL";
export const ADD_DEFAULT_SKILL = "ADD_DEFAULT_SKILL";

//List University Actions
export const GET_LIST_UNI = "SET_LIST_UNI";
export const SELECT_UNI = "SELECT_UNI";
export const SEARCH_UNI = "SEARCH_UNI";

//List Matched Job Actions
export const GET_LIST_COMPANY_FILTER = "GET_LIST_COMPANY_FILTER";
export const SEARCH_COMPANY_FILTER = "SEARCH_COMPANY_FILTER";

//Login Actions
export const SAVE_ACCOUNT = "SAVE_ACCOUNT";